In [1]:
import pandas as pd
import numpy as np
data =pd.read_csv('../Datasets/deliveries.csv')

In [7]:
data

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

#### Q.Find most districtive batsman in history of IPL
#####              Best StikeRate sr=(number_of_runs/number_of_balls )*100
#####             Batsman must have played 200 balls in 16-20 overs

In [41]:
mask=data['over']>=16
data_death_overs=data[mask]


bats=data_death_overs.groupby('batsman')
batsmansBalls=bats['batsman_runs'].count().sort_values(ascending=False)

mask2=batsmansBalls>=200
batsmansBalls=batsmansBalls[mask2]


batsmanRuns=bats['batsman_runs'].sum().sort_values(ascending=False)
sr=(batsmanRuns/batsmansBalls)*100

sr.sort_values(ascending=False).head(10)

batsman
AB de Villiers    211.052632
DA Warner         189.473684
DA Miller         186.666667
V Kohli           181.868132
RG Sharma         175.668449
DJ Hussey         175.213675
RV Uthappa        173.454545
Yuvraj Singh      171.124031
JH Kallis         170.562771
MS Dhoni          169.607843
Name: batsman_runs, dtype: float64

#### Same question using isin

In [17]:
mask=data['over']>=16
data_death_overs=data[mask]
bats=data_death_overs.groupby('batsman')
batsmansBalls=bats['batsman_runs'].count().sort_values(ascending=False)

mask2=batsmansBalls>=200
batsmansBalls=batsmansBalls[mask2]
batsman=batsmansBalls.index.tolist()

mask3=data_death_overs['batsman'].isin(batsman)#compares datasets data with list to filter 
final=data_death_overs[mask3].groupby('batsman')
final_runs=final['batsman_runs'].sum().sort_values(ascending=False)
final_balls=final['batsman_runs'].count().sort_values(ascending=False)

strikeRate=(final_runs/final_balls)*100
strikeRate.sort_values(ascending=False).head(10)

batsman
AB de Villiers    211.052632
DA Warner         189.473684
DA Miller         186.666667
V Kohli           181.868132
RG Sharma         175.668449
DJ Hussey         175.213675
RV Uthappa        173.454545
Yuvraj Singh      171.124031
JH Kallis         170.562771
MS Dhoni          169.607843
Name: batsman_runs, dtype: float64

#### Q.Find batsman with best average

In [24]:

inings_data=data.drop_duplicates(subset=['match_id','batsman'])
grouped=inings_data.groupby('batsman')
no_inings=grouped['match_id'].count().sort_index(ascending=True)
mask1=no_inings>=15
no_inings=no_inings[mask1]
batsman=no_inings.index.tolist()

mask2=data['batsman'].isin(batsman)
data1=data[mask2]
grouped1=data1.groupby('batsman')
batsman_runs=grouped1['batsman_runs'].sum().sort_index(ascending=True)
batsman_runs
avg=batsman_runs/no_inings
avg.sort_values(ascending=False).head(10)

batsman
LMP Simmons       37.206897
CH Gayle          36.510000
SE Marsh          36.072464
HM Amla           36.062500
DA Warner         35.210526
ML Hayden         34.593750
MEK Hussey        34.086207
V Kohli           31.368794
SR Tendulkar      29.923077
AB de Villiers    29.542373
dtype: float64

#### Q.Find orange cap winner of every season

In [ ]:

deliveries= pd.read_csv('../Datasets/deliveries.csv')
matches= pd.read_csv('../Datasets/matches.csv')

merged_dataset=deliveries.merge(matches,left_on='match_id',right_on='id')
a=merged_dataset.groupby(['season','batsman'])['batsman_runs'].sum()
a=a.reset_index() # converting back to data frames
a=a.sort_values('batsman_runs',ascending=False)
a.drop_duplicates(subset=['season']).sort_values('season')

      season       batsman  batsman_runs
115     2008      SE Marsh           616
229     2009     ML Hayden           572
446     2010  SR Tendulkar           618
502     2011      CH Gayle           608
684     2012      CH Gayle           733
910     2013    MEK Hussey           733
1088    2014    RV Uthappa           660
1148    2015     DA Warner           562
1383    2016       V Kohli           973
1422    2017     DA Warner           641

: